---
- import_tasks: debian.yml
  when: distribution_name == "debian" or distribution_name == "ubuntu"

- import_tasks: centos.yml
  when: distribution_name == "centos" or distribution_name == "red hat enterprise linux"

- import_tasks: fedora.yml
  when: distribution_name == "fedora"

- name: Create Docker group
  group:
    name: docker
    state: present
  register: group_result
  tags: [docker]

- name: Add USER to docker group
  user:
    append: yes
    name: "{{ item }}"
    state: present
    group: docker
  with_items:
    - vagrant
    - "{{ distribution_name }}"
  tags: [docker]

- name: Start docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: [docker]

- name: Install docker-py
  pip:
    name: docker-py
    state: present
  tags: [docker]