apiVersion: v1
kind: Service
metadata:
  name: bdb-instance-0
  namespace: default
  labels:
    name: bdb-instance-0
spec:
  selector:
    app: bdb-instance-0-dep
  ports:
  - port: 9984
    targetPort: 9984
    name: bdb-api-port
    protocol: TCP
  - port: 9985
    targetPort: 9985
    name: bdb-ws-port
    protocol: TCP
  - port: 46658
    targetPort: 46658
    name: tm-abci-port
    protocol: TCP
  type: ClusterIP
  clusterIP: None
