apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdb-instance-0-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bdb-instance-0-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bigchaindb
        image: bigchaindb/bigchaindb:2.0.0-alpha
        imagePullPolicy: Always
        args:
        - start
        env:
        - name: BIGCHAINDB_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: mdb-instance-name
        - name: BIGCHAINDB_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: mongodb-backend-port
        - name: BIGCHAINDB_DATABASE_BACKEND
          value: "localmongodb"
        - name: BIGCHAINDB_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-database-name
        - name: BIGCHAINDB_SERVER_BIND
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-server-bind
        - name: BIGCHAINDB_WSSERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-ws-interface
        - name: BIGCHAINDB_WSSERVER_ADVERTISED_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: node-fqdn
        - name: BIGCHAINDB_WSSERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-ws-port
        - name: BIGCHAINDB_WSSERVER_ADVERTISED_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: node-frontend-port
        - name: BIGCHAINDB_WSSERVER_ADVERTISED_SCHEME
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-wsserver-advertised-scheme
        - name: BIGCHAINDB_BACKLOG_REASSIGN_DELAY
          valueFrom:
            configMapKeyRef:
              name: bdb-config
              key: bigchaindb-backlog-reassign-delay
        - name: BIGCHAINDB_DATABASE_MAXTRIES
          valueFrom:
            configMapKeyRef:
              name: bdb-config
              key: bigchaindb-database-maxtries
        - name: BIGCHAINDB_DATABASE_CONNECTION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: bdb-config
              key: bigchaindb-database-connection-timeout
        - name: BIGCHAINDB_LOG_LEVEL_CONSOLE
          valueFrom:
            configMapKeyRef:
              name: bdb-config
              key: bigchaindb-log-level
        - name: BIGCHAINDB_SERVER_WORKERS
          value: "1"
        - name: BIGCHAINDB_SERVER_THREADS
          value: "1"
        - name: BIGCHAINDB_DATABASE_SSL
          value: "true"
        - name: BIGCHAINDB_DATABASE_CA_CERT
          value: /etc/bigchaindb/ca/ca.pem
        - name: BIGCHAINDB_DATABASE_CRLFILE
          value: /etc/bigchaindb/ca/crl.pem
        - name: BIGCHAINDB_DATABASE_CERTFILE
          value: /etc/bigchaindb/ssl/bdb-instance.pem
        - name: BIGCHAINDB_DATABASE_KEYFILE
          value: /etc/bigchaindb/ssl/bdb-instance.key
        - name: BIGCHAINDB_DATABASE_LOGIN
          valueFrom:
            configMapKeyRef:
              name: bdb-config
              key: bdb-user
        - name: BIGCHAINDB_TENDERMINT_HOST
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: tm-instance-name
        - name: TENDERMINT_PORT
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: tm-rpc-port
        command:
        - bash
        - "-c"
        - |
          bigchaindb -l DEBUG start
        ports:
        - containerPort: 9984
          protocol: TCP
          name: bdb-port
        - containerPort: 9985
          protocol: TCP
          name: bdb-ws-port
        - containerPort: 46658
          protocol: TCP
          name: tm-abci-port
        volumeMounts:
        - name: bdb-certs
          mountPath: /etc/bigchaindb/ssl/
          readOnly: true
        - name: ca-auth
          mountPath: /etc/bigchaindb/ca/
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: bdb-port
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: bdb-port
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
      volumes:
      - name: bdb-certs
        secret:
          secretName: bdb-certs
          defaultMode: 0400
      - name: ca-auth
        secret:
          secretName: ca-auth
          defaultMode: 0400
