---
- name: Creating files to initialize MongoDB Replica Set
  template: src=replSet_init_host.j2 dest=/tmp/replSet_init.js
  tags: [mongodb]

- name: Initializing Replica Set
  shell: "/usr/bin/mongo --host {{ ansible_hostname }} --port {{ mongodb_port }} < /tmp/replSet_init.js"
  tags: [mongodb]

- name: Adding AdminUser to MongoDB
  run_once: true
  mongodb_user:
    database: admin
    login_host: "{{ ansible_hostname }}"
    login_port: "{{ mongodb_port }}"
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: readWriteAnyDatabase,clusterManager
    state: present
  tags: [mongodb]