apiVersion: v1
kind: Service
metadata:
  name: tm-instance-1
  namespace: default
  labels:
    name: tm-instance-1
spec:
  selector:
    app: tm-instance-1-ss
  ports:
    - port: 46656
      targetPort: 46656
      name: p2p
      protocol: TCP
    - port: 46657
      targetPort: 46657
      name: rpc
      protocol: TCP
    - port: 9986
      targetPort: 9986
      name: pub-key-access
      protocol: TCP
  clusterIP: None
