apiVersion: v1
kind: Service
metadata:
  # Name of tendermint instance you are trying to connect to
  # name: "tm-instance-0"
  name: "<remote-tendermint-host>"
  namespace: default
spec:
  ports:
spec:
  ports:
  - port: 46656
    name: p2p
  - port: 46657
    name: pubkey
  type: ExternalName
  # FQDN of remote cluster/NGINX instance
  #externalName: "nginx-instance-for-tm-instance-0.westeurope.cloudapp.azure.com"
  externalName: "<dns-name-remote-nginx>"

